project_name: govm
before:
  hooks:
    - make clean
    - go mod download
builds:
-
  ldflags:
  - -s -w -X main.Version={{.Env.VERSION}}
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - 386
  goos:
  - linux
  flags:
  - -v
  main: ./main.go
archives:
-
  files:
  - ./LICENSE
  - ./README.md
  - ./img/*
  wrap_in_directory: true
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256
